name: mvcnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - black=22.6.0
  - black-jupyter=22.6.0
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cffi=1.15.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - cryptography=37.0.1
  - cudatoolkit=10.2.89
  - cytoolz=0.11.0
  - dask-core=2022.5.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=0.8.3
  - ffmpeg=4.2.2
  - flake8=4.0.1
  - freetype=2.11.0
  - fsspec=2022.3.0
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.18
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jxrlib=1.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libcurl=7.82.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libnghttp2=1.46.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.2
  - mccabe=0.7.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=2.7.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - packaging=21.3
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.9.0
  - pathtools=0.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - platformdirs=2.5.1
  - promise=2.3
  - prompt-toolkit=3.0.20
  - protobuf=3.20.1
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pyflakes=2.4.0
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pywavelets=1.3.0
  - pyzmq=22.3.0
  - readline=8.1.2
  - requests=2.27.1
  - scikit-image=0.19.2
  - scipy=1.7.3
  - sentry-sdk=1.6.0
  - setproctitle=1.2.2
  - setuptools=61.2.0
  - shortuuid=1.0.8
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.1.9
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tensorboardx=2.5.1
  - tifffile=2021.7.2
  - tk=8.6.12
  - tokenize-rt=4.2.1
  - tomli=2.0.1
  - toolz=0.11.2
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.1
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.9
  - wandb=0.12.19
  - wcwidth=0.2.5
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - pyyaml==6.0
